#Here i am in YML fuile 
#
# 
 userName:code_ByShailesh 
 password:Password@125325
 post:2020 

 #Here i have added the 1st tag now i am adding the 2nd tag 
 #
 
  userName:code_ByShailesh
  password:Password@125325
  post:2020 
 

